services:
  - type: web
    name: yt-downloader-api
    env: node
    buildCommand: |
      npm install
      python3 -m pip install yt-dlp
    startCommand: |
      export PATH="$PATH:/opt/render/.local/bin" && node server.js
